apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: frontend
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/sockets-content-management-system-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - name: frontend
          image: lucaspemaciel/frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          env:
            - name: VITE_API_URL
              value: "http://proxy-service:3001"
      restartPolicy: Always
