apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-frontend
  template:
    metadata:
      labels:
        app: cms-frontend
    spec:
      containers:
        - name: frontend
          image: lucaspemaciel/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "/api"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cms-frontend
spec:
  type: LoadBalancer
  selector:
    app: cms-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP