apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-proxy
  template:
    metadata:
      labels:
        app: cms-proxy
    spec:
      containers:
        - name: proxy
          image: lucaspemaciel/proxy:latest
          ports:
            - containerPort: 3001
          env:
            - name: SERVER_HOST
              value: "cms-server"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cms-proxy
spec:
  type: NodePort
  selector:
    app: cms-proxy
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31001 