FROM node:18 as builder
WORKDIR /app

COPY clientCMS/package.json clientCMS/package-lock.json ./
COPY clientCMS/ ./

COPY docker/.env.production .env.production

RUN npm install && npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf